In [47]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import matplotlib.colors as mcolors
import pandas as pd
import numpy as np
import os
import requests
import json
from pprint import pprint
from dotenv import load_dotenv

In [48]:
# API Call
load_dotenv()
API_KEY = os.getenv("Yelp_API") # put your key here if you don't have a .env file in your main project folder.
headers = {'Authorization': 'Bearer %s' % API_KEY}
base_url = "https://api.yelp.com/v3/businesses/search"

In [49]:
stadium_data_df = pd.read_csv('Resources/stadium_coordinates.csv', dtype={
    "NFL Team": "string",
    "City": "string",
    "State": "string",
    "Stadium Name": "string",
    "Latitude": np.float64,
    "Longitude": np.float64,
    "Zip Code": "string"
})
stadium_data_df = stadium_data_df.dropna()
stadium_data_df

,NFL Team,City,State,Stadium Name,Latitude,Longitude,Zip Code
0,Arizona Cardinals,Glendale,Arizona,State Farm Stadium,33.528000,-112.263000,85305
1,Atlanta Falcons,Atlanta,Georgia,Mercedes-Benz Stadium,33.755556,-84.400000,30313
2,Baltimore Ravens,Baltimore,Maryland,M&T Bank Stadium,39.278056,-76.622778,21230
3,Buffalo Bills,Orchard Park,New York,Bills Stadium,42.774000,-78.787000,14127
4,Carolina Panthers,Charlotte,North Carolina,Bank of America Stadium,35.225833,-80.852778,28202
5,Chicago Bears,Chicago,Illinois,Soldier Field,41.862300,-87.616700,60605
6,Cincinnati Bengals,Cincinatti,Ohio,Paul Brown Stadium,39.095000,-84.516000,45202
7,Cleveland Browns,Cleveland,Ohio,FirstEnergy Stadium,41.506111,-81.699444,44114
8,Dallas Cowboys,Arlington,Texas,AT&T Stadium,32.747778,-97.092778,76011
9,Denver Broncos,Denver,Colorado,Empower Field at Mile High,39.741000,-105.019700,80204
10,Detroit Lions,Detroit,Michigan,Ford Field,42.340000,-83.045556,48226
11,Green Bay Packers,Green Bay,Wisconsin,Lambeau Field,44.501389,-88.062222,54307
12,Houston Texans,Houston,Texas,NRG Stadium,29.684722,-95.410833,77054
13,Indianapolis Colts,Indianapolis,Indiana,Lucas Oil Stadium,39.760056,-86.163806,46225
14,Jacksonville Jaguars,Jacksonville,Florida,TIAA Bank Field,30.323889,-81.637500,32202
15,Kansas City Chiefs,Kansas City,Missouri,Arrowhead Stadium,39.048889,-94.483889,64129
16,Las Vegas Raiders,Paradise,Nevada,Allegiant Stadium,36.090833,-115.183611,89118
17,Los Angeles Chargers,Inglewood,California,SoFi Stadium,33.953450,-118.339200,90301
18,Los Angeles Rams,Inglewood,California,SoFi Stadium,33.953450,-118.339200,90301
19,Miami Dolphins,Miami Gardens,Florida,Hard Rock Stadium,25.958056,-80.238889,33056
20,Minnesota Vikings,Minneapolis,Minnessota,U.S. Bank Stadium,44.974000,-93.258000,55415
21,New England Patriots,Foxborough,Massachusetts,Gillette Stadium,42.091000,-71.264000,2035
22,New Orleans Saints,New Orleans,Louisiana,Mercedes--Benz Superdome,29.950833,-90.081111,70112
23,New York Giants,East Rutherford,New Jersey,MetLife Stadium,40.813528,-74.074361,7073
24,New York Jets,East Rutherford,New Jersey,MetLife Stadium,40.813528,-74.074361,7073
25,Philadelphia Eagles,Philadelphia,Pennsylvania,Lincoln Financial Field,39.900833,-75.167500,19101
26,Pittsburgh Steelers,Pittsburgh,Pennsylvania,Heinz Field,40.446667,-80.015833,15212
27,San Francisco 49ers,Santa Clara,California,Levi's Stadium,37.403000,-121.970000,95054
28,Seattle Seahawks,Seattle,Washington,CenturyLink Stadium,47.595200,-122.331600,98134
29,Tampa Bay Buccaners,Tampa Bay,Florida,Raymond James Stadium,27.975833,-82.503333,33607
30,Tennessee Titans,Nashville,Tennessee,Nissan Stadium,36.166389,-86.771389,37213
31,Washington Football Team,Landover,Maryland,FedEx Field,38.904663,-76.858663,20785

#Add number of businesses to the data frame
stadium_data_df["Number of restaurants"]=number_business
stadium_data_df

dollar_dict = {"$": 1, "$$": 2, "$$$": 3, "$$$$": 4}
rating_mean = []
reviews_mean = []
price_mean = []
for i in range(len(result)):
    print(i)
    # Replace $ symbols by their number of repetitions
    result[i][0] = [dollar_dict.get(dollar, dollar) for dollar in result[0][0]]
    # Remove nan values
    result[i][0] = [i for i in result[i][0] if i is not np.nan]
    #rating_mean.append(np.mean(result[i][1]))
    #reviews_mean.append(np.mean(result[i][2]))
    print(result[i][2])

In [15]:
#Replace $ characters using a dictionary
#dollar_dict = {"$": 1, "$$": 2, "$$$": 3, "$$$$": 4}
#result[0][0] = [dollar_dict.get(dollar, dollar) for dollar in result[0][0]]
#print(result[0][0])

In [16]:
#Remove np.nan from list
#result[0][0] = [i for i in result[0][0] if i is not np.nan]
#print(result[0][0])

In [50]:
# lists to store the data retrieve from Yelp
#business_name = []
#business_state = []
business_price = []
business_rating = []
business_reviews = []
number_business = []
result = []

In [51]:
counter = 0
search_limit = 20
file_list = os.listdir('json_files\Saturday')
nfl_teams = stadium_data_df["NFL Team"]
team_data = list(zip(file_list, nfl_teams))


for file, team in team_data:
    
    with open(f'json_files\Saturday\{file}', 'r', encoding = 'utf-8') as f:
        contents = json.loads(f.read())
        number_business.append(contents['total'])
        for i in range(search_limit):
            try:
                business_price.append(contents['businesses'][i]['price'])
                business_rating.append(contents['businesses'][i]['rating'])
                business_reviews.append(contents['businesses'][i]['review_count'])
                #business_name.append(contents['businesses'][i]['name'])
                #business_state.append(contents['businesses'][i]['location']['state'])
               
            except:
                business_price.append(np.nan)
                business_rating.append(np.nan)
                business_reviews.append(np.nan)
                #business_name.append(np.nan)
                #business_state.append(np.nan)
        
    result.append([
        business_price,
        business_rating,
        business_reviews,
        team
        ])
        
    #print(counter)
    #print(f'({latitude}, {longitude}, {city})')
    print(f'Total number of restaurants: {number_business[counter]}')
    
    business_price = []
    business_rating = []
    business_reviews = []
    business_name = []
    business_state = []
    print(counter, contents['total'], file)
    counter += 1

Total number of restaurants: 94
0 94 yelp_response_Arizona Cardinals.json
Total number of restaurants: 706
1 706 yelp_response_Atlanta Falcons.json
Total number of restaurants: 667
2 667 yelp_response_Baltimore Ravens.json
Total number of restaurants: 51
3 51 yelp_response_Buffalo Bills.json
Total number of restaurants: 440
4 440 yelp_response_Carolina Panthers.json
Total number of restaurants: 1400
5 1400 yelp_response_Chicago Bears.json
Total number of restaurants: 458
6 458 yelp_response_Cincinnati Bengals.json
Total number of restaurants: 354
7 354 yelp_response_Cleveland Browns.json
Total number of restaurants: 210
8 210 yelp_response_Dallas Cowboys.json
Total number of restaurants: 575
9 575 yelp_response_Denver Broncos.json
Total number of restaurants: 530
10 530 yelp_response_Detroit Lions.json
Total number of restaurants: 120
11 120 yelp_response_Green Bay Packers.json
Total number of restaurants: 180
12 180 yelp_response_Houston Texans.json
Total number of restaurants: 354
13 354 yelp_response_Indianapolis Colts.json
Total number of restaurants: 175
14 175 yelp_response_Jacksonville Jaguars.json
Total number of restaurants: 18
15 18 yelp_response_Kansas City Chiefs.json
Total number of restaurants: 758
16 758 yelp_response_Las Vegas Raiders.json
Total number of restaurants: 293
17 293 yelp_response_Los Angeles Chargers.json
Total number of restaurants: 293
18 293 yelp_response_Los Angeles Rams.json
Total number of restaurants: 84
19 84 yelp_response_Miami Dolphins .json
Total number of restaurants: 682
20 682 yelp_response_Minnesota Vikings.json
Total number of restaurants: 44
21 44 yelp_response_New England Patriots.json
Total number of restaurants: 946
22 946 yelp_response_New Orleans Saints.json
Total number of restaurants: 133
23 133 yelp_response_New York Giants.json
Total number of restaurants: 133
24 133 yelp_response_New York Jets.json
Total number of restaurants: 396
25 396 yelp_response_Philadelphia Eagles.json
Total number of restaurants: 380
26 380 yelp_response_Pittsburgh Steelers.json
Total number of restaurants: 179
27 179 yelp_response_San Francisco 49ers.json
Total number of restaurants: 1400
28 1400 yelp_response_Seattle Seahawks.json
Total number of restaurants: 270
29 270 yelp_response_Tampa Bay Buccaners.json
Total number of restaurants: 528
30 528 yelp_response_Tennessee Titans.json
Total number of restaurants: 94
31 94 yelp_response_Washington Football Team.json

In [43]:
#print(team_data)

In [52]:
print(result[0][0])

['$', '$$', '$', '$', '$$$', '$$', '$$', '$$', '$$', '$$', '$$', '$$', '$', '$', '$$', nan, nan, '$$', '$$', '$']

In [53]:
dollar_dict = {"$": 1, "$$": 2, "$$$": 3, "$$$$": 4}
rating_mean = []
reviews_mean = []
price_mean = []
for i in range(len(result)):
    print(i)
    # Replace $ symbols by their number of repetitions
    result[i][0] = [dollar_dict.get(dollar, dollar) for dollar in result[0][0]]
    # Remove nan values
    #result[i][0] = [i for i in result[i][0] if i is not np.nan]
    #result[i][1] = [i for i in result[i][0] if i is not np.nan]
    #result[i][2] = [i for i in result[i][0] if i is not np.nan]
    #rating_mean.append(np.mean(result[i][1]))
    #reviews_mean.append(np.mean(result[i][2]))
    #print(result[i][2])

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31

In [54]:
print(result)

[[[1, 2, 1, 1, 3, 2, 2, 2, 2, 2, 2, 2, 1, 1, 2, nan, nan, 2, 2, 1], [5.0, 5.0, 4.5, 4.5, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 3.5, 3.5, 4.0, 4.0, 3.5, nan, nan, 3.5, 3.5, 4.0], [73, 37, 93, 139, 392, 406, 445, 746, 650, 171, 1126, 474, 163, 103, 253, nan, nan, 443, 433, 67], 'Arizona Cardinals'], [[1, 2, 1, 1, 3, 2, 2, 2, 2, 2, 2, 2, 1, 1, 2, nan, nan, 2, 2, 1], [5.0, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.0, 4.5, 4.5, 4.0, 4.5, 4.5, 4.5], [1515, 3578, 877, 712, 3295, 572, 187, 2587, 114, 627, 754, 130, 340, 3118, 485, 121, 1652, 599, 439, 305], 'Atlanta Falcons'], [[1, 2, 1, 1, 3, 2, 2, 2, 2, 2, 2, 2, 1, 1, 2, nan, nan, 2, 2, 1], [4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 5.0, 4.5, 4.5, 4.5, nan, 4.5, 4.5, 4.5, 4.5], [711, 211, 380, 186, 175, 721, 161, 495, 411, 394, 410, 63, 195, 537, 240, nan, 127, 216, 293, 202], 'Baltimore Ravens'], [[1, 2, 1, 1, 3, 2, 2, 2, 2, 2, 2, 2, 1, 1, 2, nan, nan, 2, 2, 1], [4.5, 4.5, nan, 4.5, 4.0, 4.0, 4.0, 3.5, 3.5, 3.5, 4.0, 4.0, 3.5, 3.5, nan, 3.5, 3.0, 3.0, 3.0, 3.0], [77, 167, nan, 52, 91, 55, 52, 112, 75, 68, 30, 29, 57, 29, nan, 50, 79, 65, 63, 39], 'Buffalo Bills'], [[1, 2, 1, 1, 3, 2, 2, 2, 2, 2, 2, 2, 1, 1, 2, nan, nan, 2, 2, 1], [4.5, 4.5, 4.5, 4.5, 4.5, 5.0, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, nan, 4.5, 4.5], [273, 955, 413, 642, 519, 58, 394, 215, 340, 208, 759, 285, 82, 533, 339, 193, 427, nan, 487, 177], 'Carolina Panthers'], [[1, 2, 1, 1, 3, 2, 2, 2, 2, 2, 2, 2, 1, 1, 2, nan, nan, 2, 2, 1], [4.5, 5.0, 4.5, 5.0, 4.5, nan, 4.5, 4.5, 5.0, 4.5, 4.5, 5.0, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5], [2382, 115, 948, 57, 7509, nan, 603, 2484, 81, 1179, 112, 46, 670, 1155, 443, 574, 381, 808, 1389, 217], 'Chicago Bears'], [[1, 2, 1, 1, 3, 2, 2, 2, 2, 2, 2, 2, 1, 1, 2, nan, nan, 2, 2, 1], [4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 5.0, 4.5, 4.5, 4.5, 4.5, nan, 4.5], [1090, 2018, 214, 1351, 442, 367, 232, 308, 215, 532, 134, 389, 722, 45, 986, 249, 301, 1225, nan, 248], 'Cincinnati Bengals'], [[1, 2, 1, 1, 3, 2, 2, 2, 2, 2, 2, 2, 1, 1, 2, nan, nan, 2, 2, 1], [5.0, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.0, 4.5, 4.0, 4.5, 4.5, 4.5, 4.5, 4.0, 4.5], [94, 190, 290, 230, 265, 499, 121, 215, 143, 368, 96, 1109, 61, 1417, 303, 122, 88, 253, 787, 267], 'Cleveland Browns'], [[1, 2, 1, 1, 3, 2, 2, 2, 2, 2, 2, 2, 1, 1, 2, nan, nan, 2, 2, 1], [4.5, 4.5, 4.5, 4.5, 4.5, 4.0, nan, 4.0, 4.0, 4.5, 4.0, 4.5, nan, 4.0, 4.0, 4.0, nan, 4.5, 4.5, 4.5], [149, 972, 280, 186, 150, 379, nan, 340, 642, 106, 461, 120, nan, 186, 322, 272, nan, 41, 43, 64], 'Dallas Cowboys'], [[1, 2, 1, 1, 3, 2, 2, 2, 2, 2, 2, 2, 1, 1, 2, nan, nan, 2, 2, 1], [4.5, 4.5, 4.5, 5.0, 5.0, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5], [331, 281, 304, 96, 73, 629, 207, 133, 3365, 201, 303, 181, 350, 282, 553, 669, 2216, 608, 232, 383], 'Denver Broncos'], [[1, 2, 1, 1, 3, 2, 2, 2, 2, 2, 2, 2, 1, 1, 2, nan, nan, 2, 2, 1], [4.5, nan, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.0, nan, 4.5, nan, 4.5, 5.0, 4.0, 4.5], [679, nan, 1487, 874, 415, 1125, 107, 194, 538, 155, 883, 894, 1884, nan, 312, nan, 49, 37, 544, 259], 'Detroit Lions'], [[1, 2, 1, 1, 3, 2, 2, 2, 2, 2, 2, 2, 1, 1, 2, nan, nan, 2, 2, 1], [4.0, 4.5, 4.5, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 3.5, 3.5, 3.5, nan, 4.0, 3.5, 4.0, 3.5], [269, 85, 103, 127, 424, 84, 114, 90, 102, 117, 58, 31, 99, 282, 89, nan, 45, 90, 26, 98], 'Green Bay Packers'], [[1, 2, 1, 1, 3, 2, 2, 2, 2, 2, 2, 2, 1, 1, 2, nan, nan, 2, 2, 1], [4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.0, 4.0, 4.0, 4.0, 4.0, 4.5, 4.0, 4.0, 4.0, 4.0, nan, 4.5], [546, 289, 323, 450, 768, 746, 155, 309, 534, 343, 186, 307, 249, 40, 111, 160, 213, 148, nan, 42], 'Houston Texans'], [[1, 2, 1, 1, 3, 2, 2, 2, 2, 2, 2, 2, 1, 1, 2, nan, nan, 2, 2, 1], [5.0, 5.0, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.0], [175, 193, 309, 338, 1971, 163, 208, 790, 632, 927, 478, 1541, 1533, 174, 693, 135, 151, 293, 226, 1513], 'Indianapolis Colts'], [[1, 2, 1, 1, 3, 2, 2, 2, 2, 2, 2, 2, 1, 1, 2, nan, nan, 2, 2, 1], [4.5, 4.5, 5.0, 4.5, 4.5, 5.0, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.0, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5], [940, 631, 61, 981, 705, 57, 218, 151, 253, 159, 68, 62, 137, 384, 221, 124, 111, 134, 44, 79], 'Jacksonville Jaguars'], [[1, 2, 1, 1, 3, 2, 2, 2, 2, 2, 2, 2, 1, 1, 2, nan, nan, 2, 2, 1], [4.5, 4.0, 4.5, 4.0, 4.0, 4.5, 3.5, nan, 2.0, 2.5, nan, nan, 2.5, 2.0, 2.5, nan, nan, 1.5, nan, nan], [41, 132, 30, 144, 52, 5, 7, nan, 31, 9, nan, nan, 7, 9, 3, nan, nan, 11, nan, nan], 'Kansas City Chiefs'], [[1, 2, 1, 1, 3, 2, 2, 2, 2, 2, 2, 2, 1, 1, 2, nan, nan, 2, 2, 1], [5.0, 4.5, 4.5, 4.5, 4.5, 5.0, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 5.0, 4.5, 4.5, 4.5, 4.5, 4.5, nan, 4.5], [126, 370, 482, 5278, 2184, 94, 168, 133, 429, 168, 5072, 573, 65, 589, 5672, 1068, 921, 1022, nan, 2991], 'Las Vegas Raiders'], [[1, 2, 1, 1, 3, 2, 2, 2, 2, 2, 2, 2, 1, 1, 2, nan, nan, 2, 2, 1], [4.5, 5.0, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 5.0, 4.5, 4.5, nan, 4.5, 4.0, 4.0, 4.5, 4.5, 4.5, 4.0, 4.0], [231, 138, 244, 707, 161, 1347, 1961, 269, 69, 113, 90, nan, 582, 759, 636, 104, 137, 123, 636, 949], 'Los Angeles Chargers'], [[1, 2, 1, 1, 3, 2, 2, 2, 2, 2, 2, 2, 1, 1, 2, nan, nan, 2, 2, 1], [4.5, 5.0, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 5.0, 4.5, 4.5, nan, 4.5, 4.0, 4.0, 4.5, 4.5, 4.5, 4.0, 4.0], [231, 138, 244, 707, 161, 1347, 1961, 269, 69, 113, 90, nan, 582, 759, 636, 104, 137, 123, 636, 949], 'Los Angeles Rams'], [[1, 2, 1, 1, 3, 2, 2, 2, 2, 2, 2, 2, 1, 1, 2, nan, nan, 2, 2, 1], [4.5, 4.5, 4.5, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 3.5, 4.0, nan, 4.0, 3.5, 4.0, 4.0, nan, nan, 3.5, nan], [173, 117, 60, 55, 117, 68, 46, 49, 82, 266, 39, nan, 17, 37, 14, 21, nan, nan, 60, nan], 'Miami Dolphins '], [[1, 2, 1, 1, 3, 2, 2, 2, 2, 2, 2, 2, 1, 1, 2, nan, nan, 2, 2, 1], [5.0, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 5.0, 4.5, 4.5, 4.5, 4.5], [126, 377, 118, 329, 1271, 1172, 917, 719, 821, 146, 977, 121, 93, 983, 549, 39, 238, 941, 187, 530], 'Minnesota Vikings'], [[1, 2, 1, 1, 3, 2, 2, 2, 2, 2, 2, 2, 1, 1, 2, nan, nan, 2, 2, 1], [4.0, 4.0, nan, 3.5, 4.0, 4.0, 3.5, 3.5, 3.0, 4.0, 3.5, 3.5, nan, 3.5, 3.5, 4.0, nan, nan, 3.0, 3.5], [164, 96, nan, 339, 90, 97, 291, 195, 290, 33, 67, 76, nan, 73, 50, 27, nan, nan, 85, 24], 'New England Patriots'], [[1, 2, 1, 1, 3, 2, 2, 2, 2, 2, 2, 2, 1, 1, 2, nan, nan, 2, 2, 1], [5.0, 4.5, 5.0, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 5.0, 4.5, 4.5, 4.5, 4.5], [172, 498, 125, 328, 717, 2203, 475, 415, 3667, 208, 345, 293, 208, 312, 779, 117, 2008, 1320, 800, 1987], 'New Orleans Saints'], [[1, 2, 1, 1, 3, 2, 2, 2, 2, 2, 2, 2, 1, 1, 2, nan, nan, 2, 2, 1], [4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.0, 4.5, 4.5, 4.5, 4.0, 4.5, 4.0, 4.5, 4.0, 4.5, 4.0, 4.0, 4.0, nan], [266, 227, 526, 264, 79, 138, 251, 37, 61, 124, 264, 57, 101, 45, 116, 66, 154, 106, 423, nan], 'New York Giants'], [[1, 2, 1, 1, 3, 2, 2, 2, 2, 2, 2, 2, 1, 1, 2, nan, nan, 2, 2, 1], [4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.0, 4.5, 4.5, 4.5, 4.0, 4.5, 4.0, 4.5, 4.0, 4.5, 4.0, 4.0, 4.0, nan], [266, 227, 526, 264, 79, 138, 251, 37, 61, 124, 264, 57, 101, 45, 116, 66, 154, 106, 423, nan], 'New York Jets'], [[1, 2, 1, 1, 3, 2, 2, 2, 2, 2, 2, 2, 1, 1, 2, nan, nan, 2, 2, 1], [4.5, 4.5, 5.0, 4.5, 5.0, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5], [526, 534, 117, 202, 45, 157, 382, 352, 341, 327, 200, 1450, 353, 84, 408, 118, 77, 139, 252, 341], 'Philadelphia Eagles'], [[1, 2, 1, 1, 3, 2, 2, 2, 2, 2, 2, 2, 1, 1, 2, nan, nan, 2, 2, 1], [4.5, 4.5, 5.0, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, nan, 4.5, 4.5, 4.5, 4.0, 4.5, 4.5, 4.5, 4.0, 4.0, 4.5], [2012, 441, 66, 187, 130, 116, 619, 1544, 67, nan, 284, 713, 999, 846, 139, 176, 96, 720, 2027, 138], 'Pittsburgh Steelers'], [[1, 2, 1, 1, 3, 2, 2, 2, 2, 2, 2, 2, 1, 1, 2, nan, nan, 2, 2, 1], [nan, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.0, 4.0, 4.0, 4.5, 4.0, 4.5, 4.5, 4.0, 4.0, 4.5, 4.0], [nan, 146, 1188, 1394, 745, 379, 119, 117, 322, 488, 1404, 1562, 98, 249, 193, 52, 2289, 663, 73, 195], 'San Francisco 49ers'], [[1, 2, 1, 1, 3, 2, 2, 2, 2, 2, 2, 2, 1, 1, 2, nan, nan, 2, 2, 1], [5.0, 4.5, 4.5, 4.5, nan, 4.5, 5.0, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 5.0, 4.5, 4.5, 4.5, 4.5, 4.5], [177, 837, 692, 1709, nan, 260, 66, 956, 185, 1368, 204, 244, 2329, 1066, 111, 230, 123, 7381, 198, 251], 'Seattle Seahawks'], [[1, 2, 1, 1, 3, 2, 2, 2, 2, 2, 2, 2, 1, 1, 2, nan, nan, 2, 2, 1], [5.0, 5.0, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.0, nan, 4.5, 4.5, 4.0, 4.5], [166, 144, 247, 320, 287, 177, 611, 524, 155, 668, 250, 486, 87, 950, 673, nan, 425, 224, 497, 194], 'Tampa Bay Buccaners'], [[1, 2, 1, 1, 3, 2, 2, 2, 2, 2, 2, 2, 1, 1, 2, nan, nan, 2, 2, 1], [5.0, 4.5, 5.0, 4.5, 4.5, 4.5, nan, 4.5, 4.5, 5.0, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5], [360, 1458, 138, 1193, 809, 1248, nan, 5562, 2253, 112, 391, 370, 143, 351, 1098, 946, 1386, 962, 171, 149], 'Tennessee Titans'], [[1, 2, 1, 1, 3, 2, 2, 2, 2, 2, 2, 2, 1, 1, 2, nan, nan, 2, 2, 1], [4.5, 4.5, 4.0, 4.0, 4.5, 4.5, 3.5, 3.5, 3.5, 4.0, 3.5, 3.5, 3.0, nan, 3.0, nan, nan, 3.0, 4.0, 4.5], [336, 63, 134, 172, 32, 53, 718, 215, 146, 34, 97, 67, 434, nan, 367, nan, nan, 451, 17, 9], 'Washington Football Team']]